#!/bin/sh

if systemctl -q is-active incus.service; then
    exit 0
fi

if [ "${USE_SYSLOG:-no}" = 'no' ]; then
    exec /usr/libexec/incus/incusd --group incus-admin --logfile=/var/log/incus/incus.log
else
    exec /usr/libexec/incus/incusd --group incus-admin --syslog
fi
